plugins:
  - jest
env:
  es2022: true
  node: true
  browser: true
  jest: true
extends:
  - airbnb
  - airbnb/hooks
  - airbnb-typescript
  - plugin:jest/recommended
ignorePatterns:
  - dist/
  - coverage/
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: './tsconfig.eslint.json'
rules:
  no-console: 'warn'
  object-curly-newline: 'off'
  import/extensions: 'off'
  import/prefer-default-export: 'off'
  class-methods-use-this: 'off'
  jsx-a11y/label-has-associated-control:
  - error
  - controlComponents:
    - Input
    assert: htmlFor
    depth: 3
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: '^_'
  '@typescript-eslint/indent': 'off'
